sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8

env:
  global:
  - DOCKER_USERNAME=cytomineulg
  - secure: "ayBiBrJYyS/UodG18hyngV2DN3XZWqLver3EPd/JVeSv2U18pNO2zkA3d1GKy65OBHQ5QTNnr+8u7HfjMBoyZboFM9wXfJrVzqJVL+xpRY7DL9xedX3EQSYByppLHDLUYbyd+W8fd1eBOCe90YfWBBXHPWYksUxTTx6b2izgUFeZWXQBODWaSQKUmegjzJsg0mgVX6KwIQx2fstethoZhJI6Rr8VqvksMYpb4KRE1IFWnkZvimYgsodwar5HAoi49cm6UhnP7szxUiryr8JS3K1AMufOVRJaL4bh6I2XjygSt8c/V8ywhokztXeuouQLdsXCVN63fDfdg1z5dDwq4S05yiVsii+4bte/cXjyCk+cUi1jxaUQUzTMTcTWs8WNoPFBrBc8TZg7g8DktqOu0dNL9x6nCQ5ksd/b+/oG60Me5scIKXGMI+ce5+m5rJg4BBqOD2TkbuhAD3PC743ikk0p5ClWbB2UVihxA82m2ZCP3UxJdbsOzCN51PEnJa0JWfN8b+6r0XHoAQB7EAGIeZanwDXHh03zQeNtgxE+tNGvAJW4UnkgJJY3m3yM332KO6Kdx63WfL+YYDb6ZgcvHORmutqB90SQXjZhzYV56+chzd22KA6gOL7CLPqnJxcZjHMG/3yFhKoIjbnj02wbNmI8Pi2xSERxssA0L5TEg4E="

script: true

after_success:
  - git fetch --tags
  - export VERSION=$(gradle properties -q | grep "version:" | awk '{print $2}' | tr -d '[:space:]')
  - export DEPLOY=false
  - >
    if [[ ! $(git tag -l v$VERSION) ]]; then
      git config --local user.name "$(git log -1 --pretty=format:'%an')";
      git config --local user.email "$(git log -1 --pretty=format:'%ae')";
      git tag "v$VERSION";
      export DEPLOY=true;
      echo "Deploy with version $VERSION";
      ./gradlew jar;
      mv build/libs/cytomine-bioformats-wrapper-$VERSION.jar cytomine-bioformats-wrapper.jar;
      cp cytomine-bioformats-wrapper.jar docker/;
      docker build --build-arg RELEASE_PATH="." --build-arg FROM_NAMESPACE=cytomineuliege --build-arg FROM_VERSION=v1.2.0 -t cytomineuliege/bioformat:latest -t cytomineuliege/bioformat:v$VERSION docker/
    fi;

deploy:
  - provider: script
    script: >
      echo $VERSION &&
      docker login -u "$DOCKER_USERNAME" -p $"DOCKER_PASSWORD' &&
      docker push cytomineuliege/bioformat:v$VERSION &&
      echo "Done."
    skip_cleanup: true
    on:
      condition: $DEPLOY = true
  - provider: releases
    api_key:
      secure: TPQa8EpiTwijPQUjMvJuo1QrkpDrBOxwmkGsJ4A7L+8JhAs2c9OVs3iyPwlxwrUHgglC3kOGq0HVtY7vZrBY/FTCeKuKFjCEjsDHeioulYDFK4oV55vQQeLks65Xr1gbXE42TnzluGjsREAMOjywf4JhyhqmKC424YGtY2ZOuaAbHSNOtzl6I9rwnezXSSY3Kzdudo9zS0pq+L4QUHxRYh50hHdv/vyhaEpMCZiIowtXign348PdkRRjmGwQKlPB6L0oY+lbxA35vTb+WALOmrNLbyyG55WnjXSWnL3cn8KDmllLcNmhzXDldsDGPph2fTP65XieVRuUqvTb38837JhlDe9nvz5Msd9JNlMP04vxKcGhZnVoPUVPfRmZCItzeOrvwOUt1V99BJ4uJeQVxR0W2ZcJ9KvC4UbBG1+FNBMpB+jqZg76aQqTLJjJHRXbTGj/wskGR0Gw/yvjZCyydCeMWVNPp8i+NHmh+RQu69DkYfRzoVi5EynutyIzY3OkZZ4N8lezN3nUNxRghOBZXc6wSJdhJpMmIigvjKqxBZONZ3u3qpH/JashQkTNZLfS2vsQ0Uzz4of24QysQ7rm9yTS3ZyCB5GU11P82Hm2SzScVf+OiQFGjLpb19jk+t9SPMyY23cpvT5s38HIY5wWGceb7NcQtwI1ycOVd7HnoZ0=
    file:
      - cytomine-bioformats-wrapper.jar
    skip_cleanup: true
    on:
      condition: $DEPLOY = true

notifications:
  email: false
  slack:
    secure: TrdyGx56LOXEzrMxZgMhnYwpLQjIX3fL40YYujq40W66Rcis6nm2SP4i0By3fOSwwKcRwP8HXvs219sZddL3KJSZ0ormMvLHVjo9NNEbUAHqWVUBnaNJjF6ANmRFpuIKkVRTu2LQHaJhjMFyrKg8VVRAxNR1keaOsVeb4/U6gLF9LqfMciz56TtoDzfbMfB0V7l+RtUfRpeKGjDqp+lAEIzueSRItK49hP4gACGxJEMACIG+z1PZNLtVTnV6DokqnVmhUBIo9+ikLmU8g48Ark6hmj0JC5zZHK+LwZUhlMeJmPsJMydJ0ZPiOzcdPhQoLZC5looGFYPru2Igu3GTIM/hoTCDIYUCYRStr0vRF4niEEWMXKp9NJUQHkK0RwPCsuc0iwl1Jaeh9+qSEUeEW3tYyRgNwBPI4YK/XFt1/oDHufi8xU50xVTysSOxVJWbZ29OVdJ4LtWrF5rdKiFfl54sAqEnVREp8QcvRFXLMwL89cW5omi4xqmlojLm1pS/6DthlrED7dMz8qQi43shOPQbVqA+TRRUXl7jPo4DNTbI/8KfJGXg76scytZB4qUx4t6j2C9YxllHEZf7nlNyvHQzTLrcNOB6kxYFOibdrWIm1TycpbIBkb3l/1ZP0MgVFLpEu89eYcCpk29g6QkdyMU6Pb69avq4c9HUk0WhGME=
