sudo: required

dist: trusty

services:
  - docker

language: java

jdk:
  - oraclejdk8

env:
  global:
  - DOCKER_USERNAME=cytomineulg
  - secure: "Jwdb9/zNClvneLnqN4tpw4Gxvl+9pn2I36hek7VC1ggxXYHvYux1tMocSl4F9//JpOkjayA4y343nuXdKhi4W6BSQvIDeK/sU6I1z8DsjRaX5ZZ30vu85qlJ/EeBqK/xn2AyKP7Z0vIIDhgTlik1URur2DMNTA7a6rhvJeSQIjgOZ1GU5O1xAFMd4LXgzQKa+xbXCk1qRB74oo7eTDh8N4w+xvp/mRZDAfgqVUhgQopsk/ecOr+iOKPZUvJZm5LsJVCKqiaGX1jdzpfZNUrXdkwc2LpWaVx9sY/5p/442Hk4JNyf7GHB3agHjl3Pg2GJuT5Nj9EP4pRa18ay9hUNxjLBf851i70NYqAMOuSk49bWSx17VjJp1KZBXTCxDFHv46hh3iQsKLq68PYumlt4G0J8uKty4pV+V8W6aM420E6GO3eae0yhMAkO7FIRZevk0wmOX5UcUQZe1Va/+mDOndwJcgVHobcVI0Ittw+XgOfl/ZqCgGqor6Q+peZL4o8jPqQyMoEEx7TloHPW7AqRR65ywejBeKRJpdvJushE8nz+BmrYfVMW/oZEtuydJLKAk3iHqqgFDWYU2xCC7aKGI/aa4BJhWVYlNSKf59ys74becyyMXYxd+cKS2n857MjYLDeJcMKbaOQ4iDCrCXqhkuTZljgdbY3tfPa1cxRrKHw="

script: true

after_success:
  - git fetch --tags
  - export VERSION=$(gradle properties -q | grep "version:" | awk '{print $2}' | tr -d '[:space:]')
  - export DEPLOY=false
  - >
    if [[ ! $(git tag -l v$VERSION) ]]; then
      git config --local user.name "$(git log -1 --pretty=format:'%an')";
      git config --local user.email "$(git log -1 --pretty=format:'%ae')";
      git tag "v$VERSION";
      export DEPLOY=true;
      echo "Deploy with version $VERSION";
      ./gradlew jar;
      mv build/libs/cytomine-bioformats-wrapper-$VERSION.jar cytomine-bioformats-wrapper.jar;
      cp cytomine-bioformats-wrapper.jar docker/;
      docker build --build-arg RELEASE_PATH="." --build-arg FROM_NAMESPACE=cytomineuliege --build-arg FROM_VERSION=v1.2.0 -t cytomineuliege/bioformat:latest -t cytomineuliege/bioformat:v$VERSION docker/
    fi;

deploy:
  - provider: script
    script: >
      echo $VERSION &&
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
      docker push cytomineuliege/bioformat:v$VERSION &&
      echo "Done."
    skip_cleanup: true
    on:
      condition: $DEPLOY = true
  - provider: releases
    api_key:
      secure: TPQa8EpiTwijPQUjMvJuo1QrkpDrBOxwmkGsJ4A7L+8JhAs2c9OVs3iyPwlxwrUHgglC3kOGq0HVtY7vZrBY/FTCeKuKFjCEjsDHeioulYDFK4oV55vQQeLks65Xr1gbXE42TnzluGjsREAMOjywf4JhyhqmKC424YGtY2ZOuaAbHSNOtzl6I9rwnezXSSY3Kzdudo9zS0pq+L4QUHxRYh50hHdv/vyhaEpMCZiIowtXign348PdkRRjmGwQKlPB6L0oY+lbxA35vTb+WALOmrNLbyyG55WnjXSWnL3cn8KDmllLcNmhzXDldsDGPph2fTP65XieVRuUqvTb38837JhlDe9nvz5Msd9JNlMP04vxKcGhZnVoPUVPfRmZCItzeOrvwOUt1V99BJ4uJeQVxR0W2ZcJ9KvC4UbBG1+FNBMpB+jqZg76aQqTLJjJHRXbTGj/wskGR0Gw/yvjZCyydCeMWVNPp8i+NHmh+RQu69DkYfRzoVi5EynutyIzY3OkZZ4N8lezN3nUNxRghOBZXc6wSJdhJpMmIigvjKqxBZONZ3u3qpH/JashQkTNZLfS2vsQ0Uzz4of24QysQ7rm9yTS3ZyCB5GU11P82Hm2SzScVf+OiQFGjLpb19jk+t9SPMyY23cpvT5s38HIY5wWGceb7NcQtwI1ycOVd7HnoZ0=
    file:
      - cytomine-bioformats-wrapper.jar
    skip_cleanup: true
    on:
      condition: $DEPLOY = true

notifications:
  email: false
  slack:
    secure: TrdyGx56LOXEzrMxZgMhnYwpLQjIX3fL40YYujq40W66Rcis6nm2SP4i0By3fOSwwKcRwP8HXvs219sZddL3KJSZ0ormMvLHVjo9NNEbUAHqWVUBnaNJjF6ANmRFpuIKkVRTu2LQHaJhjMFyrKg8VVRAxNR1keaOsVeb4/U6gLF9LqfMciz56TtoDzfbMfB0V7l+RtUfRpeKGjDqp+lAEIzueSRItK49hP4gACGxJEMACIG+z1PZNLtVTnV6DokqnVmhUBIo9+ikLmU8g48Ark6hmj0JC5zZHK+LwZUhlMeJmPsJMydJ0ZPiOzcdPhQoLZC5looGFYPru2Igu3GTIM/hoTCDIYUCYRStr0vRF4niEEWMXKp9NJUQHkK0RwPCsuc0iwl1Jaeh9+qSEUeEW3tYyRgNwBPI4YK/XFt1/oDHufi8xU50xVTysSOxVJWbZ29OVdJ4LtWrF5rdKiFfl54sAqEnVREp8QcvRFXLMwL89cW5omi4xqmlojLm1pS/6DthlrED7dMz8qQi43shOPQbVqA+TRRUXl7jPo4DNTbI/8KfJGXg76scytZB4qUx4t6j2C9YxllHEZf7nlNyvHQzTLrcNOB6kxYFOibdrWIm1TycpbIBkb3l/1ZP0MgVFLpEu89eYcCpk29g6QkdyMU6Pb69avq4c9HUk0WhGME=
